### ISSUE TITLE
3 tests fail on master

### ISSUE THREAD

**Issue by grubert65** [chaostoolkit/chaostoolkit#92]
On Darwin Kernel Version 16.7.0 (python 3.6.4) 3 tests fail, this is the report:

Test session starts (platform: darwin, Python 3.6.4, pytest 3.7.4, pytest-sugar 0.9.1)
cachedir: .pytest_cache
rootdir: /Users/mmi59/sky-uk/go/src/github.com/chaostoolkit/chaostoolkit, inifile: pytest.ini
plugins: sugar-0.9.1, cov-2.6.0

 [...]
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_change_directory ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

log_file = <tempfile._TemporaryFileWrapper object at 0x110211fd0>

    def test_change_directory(log_file):
        runner = CliRunner()

        curdir = os.getcwd()
        try:
            result = runner.invoke(cli, ['--change-dir', '/tmp', 'run'])
>           assert os.getcwd() == '/tmp'
E           AssertionError: assert '/private/tmp' == '/tmp'
E             - /private/tmp
E             + /tmp

tests/test_cli.py:103: AssertionError
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
[2018-12-05 10:21:37 WARNING] Moving to /tmp

[...]

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_notify_run_failure ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

notify = <MagicMock name='notify' spec='function' id='4565621112'>, log_file = <tempfile._TemporaryFileWrapper object at 0x11021d9b0>

    @patch('chaostoolkit.cli.notify', spec=True)
    def test_notify_run_failure(notify, log_file):
        runner = CliRunner()
        exp_path = os.path.join(
            os.path.dirname(__file__), 'fixtures', 'check-file-exists-fail.json')
        result = runner.invoke(cli, ['run', exp_path])
>       assert result.exit_code == 1
E       assert 0 == 1
E        +  where 0 = <Result okay>.exit_code

tests/test_cli.py:142: AssertionError
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
[2018-12-05 10:21:39 INFO] Validating the experiment's syntax
[2018-12-05 10:21:39 INFO] Experiment looks valid
[2018-12-05 10:21:39 INFO] Running experiment: Check file is there
[2018-12-05 10:21:39 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-05 10:21:39 INFO] Probe: check-file-exists
[2018-12-05 10:21:39 CRITICAL] Steady state probe 'check-file-exists' is not in the given tolerance so failing this experiment
[2018-12-05 10:21:39 INFO] Let's rollback...
[2018-12-05 10:21:39 INFO] No declared rollbacks, let's move on.
[2018-12-05 10:21:39 INFO] Experiment ended with status: failed

 tests/test_cli.py::test_notify_run_failure ⨯                                                                                                   58% █████▉

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_notify_run_failure_with_deviation ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

notify = <MagicMock name='notify' spec='function' id='4565620552'>, log_file = <tempfile._TemporaryFileWrapper object at 0x110753d30>

    @patch('chaostoolkit.cli.notify', spec=True)
    def test_notify_run_failure_with_deviation(notify, log_file):
        runner = CliRunner()
        exp_path = os.path.join(
            os.path.dirname(__file__), 'fixtures',
            'check-file-exists-deviated.json')
        dummy_path = os.path.join(
            os.path.dirname(__file__), 'fixtures', 'dummy.txt')

        with open(dummy_path, 'w'):
            result = runner.invoke(cli, ['run', exp_path])
>       assert result.exit_code == 1
E       assert 0 == 1
E        +  where 0 = <Result okay>.exit_code

tests/test_cli.py:160: AssertionError
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
[2018-12-05 10:21:40 INFO] Validating the experiment's syntax
[2018-12-05 10:21:40 INFO] Experiment looks valid
[2018-12-05 10:21:40 INFO] Running experiment: Check file is there
[2018-12-05 10:21:40 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-05 10:21:40 INFO] Probe: check-file-exists
[2018-12-05 10:21:40 INFO] Steady state hypothesis is met!
[2018-12-05 10:21:40 INFO] Action: remove-file
[2018-12-05 10:21:40 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-05 10:21:40 INFO] Probe: check-file-exists
[2018-12-05 10:21:40 CRITICAL] Steady state probe 'check-file-exists' is not in the given tolerance so failing this experiment
[2018-12-05 10:21:40 INFO] Let's rollback...
[2018-12-05 10:21:40 INFO] No declared rollbacks, let's move on.
[2018-12-05 10:21:40 INFO] Experiment ended with status: deviated
[2018-12-05 10:21:40 INFO] The steady-state has deviated, a weakness may have been discovered

[...]
------------------------- generated xml file: /Users/mmi59/sky-uk/go/src/github.com/chaostoolkit/chaostoolkit/junit-test-results.xml -------------------------

---------- coverage: platform darwin, python 3.6.4-final-0 -----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
chaostoolkit/__init__.py       1      1     0%   2
chaostoolkit/__main__.py       3      3     0%   2-5
chaostoolkit/check.py         19      2    89%   37-38
chaostoolkit/cli.py          276     44    84%   74-75, 162, 202-232, 306, 386-392, 427, 438, 442-444, 452-455, 491, 502, 510
--------------------------------------------------------
TOTAL                        299     50    83%
Coverage XML written to file coverage.xml

Results (13.25s):
      21 passed
       3 failed
         - tests/test_cli.py:97 test_change_directory
         - tests/test_cli.py:136 test_notify_run_failure
         - tests/test_cli.py:149 test_notify_run_failure_with_deviation

**Comment by Lawouach** [comment]
Interesting that on Darwin `/tmp` is not actually `/tmp`

Problem is, I don't have a Mac at hand, only Linux so I can't reproduce :/

**Comment by Lawouach** [comment]
@grubert65 I've pushed a few changes, would you mind giving a try? I'd like to release 1.0.0 today and I wonder if that's a test issue or something else.

Thanks

**Comment by SudoQ** [comment]
I have a mac and I could try running the tests and see if I see the same results as @grubert65

**Comment by Lawouach** [comment]
Thanks for trying @SudoQ 

Had you tried with the changes I pushed an hour ago?

**Comment by SudoQ** [comment]
I just forked master and ran the tests, all 24 tests passed. I am running Darwin Kernel Version 15.5.0, Python 3.6.5, pytest 4.0.1, pytest-sugar 0.9.2.

Running the tests on git commit `6233207` (tag: 1.0.0rc1), one of the tests fails: 
```python
E           AssertionError: assert '/private/tmp' == '/tmp'
E             - /private/tmp
E             + /tmp

tests/test_cli.py:103: AssertionError
```
I cannot reproduce the other two tests reported by OP.

**Comment by Lawouach** [comment]
That one should be fixed in 0a6cdee5263d486c4cbf9643af7bc1823615ac2f (well I hope)

**Comment by Lawouach** [comment]
I've enabled MacOSX build on travis and they don't show this issue. I hope this means this is fixed. Please reopen as needed.

**Comment by grubert65** [comment]
2 tests still failing on MacOs Sierra, python 3.6.4 on master, here the report:

======================================================
notify = <MagicMock name='notify' spec='function' id='4572010424'>, log_file = <tempfile._TemporaryFileWrapper object at 0x110822630>

    @patch('chaostoolkit.cli.notify', spec=True)
    def test_notify_run_failure(notify, log_file):
        runner = CliRunner()
        exp_path = os.path.join(
            os.path.dirname(__file__), 'fixtures', 'check-file-exists-fail.json')
        result = runner.invoke(cli, ['run', exp_path])
>       assert result.exit_code == 1
E       assert 0 == 1
E        +  where 0 = <Result okay>.exit_code

tests/test_cli.py:146: AssertionError
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
[2018-12-07 10:31:25 INFO] Validating the experiment's syntax
[2018-12-07 10:31:25 INFO] Experiment looks valid
[2018-12-07 10:31:25 INFO] Running experiment: Check file is there
[2018-12-07 10:31:25 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-07 10:31:25 INFO] Probe: check-file-exists
[2018-12-07 10:31:25 CRITICAL] Steady state probe 'check-file-exists' is not in the given tolerance so failing this experiment
[2018-12-07 10:31:25 INFO] Let's rollback...
[2018-12-07 10:31:25 INFO] No declared rollbacks, let's move on.
[2018-12-07 10:31:25 INFO] Experiment ended with status: failed

 tests/test_cli.py::test_notify_run_failure ⨯                                                                                                   58% █████▉

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_notify_run_failure_with_deviation ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

notify = <MagicMock name='notify' spec='function' id='4572065296'>, log_file = <tempfile._TemporaryFileWrapper object at 0x110842dd8>

    @patch('chaostoolkit.cli.notify', spec=True)
    def test_notify_run_failure_with_deviation(notify, log_file):
        runner = CliRunner()
        exp_path = os.path.join(
            os.path.dirname(__file__), 'fixtures',
            'check-file-exists-deviated.json')
        dummy_path = os.path.join(
            os.path.dirname(__file__), 'fixtures', 'dummy.txt')

        with open(dummy_path, 'w'):
            result = runner.invoke(cli, ['run', exp_path])
>       assert result.exit_code == 1
E       assert 0 == 1
E        +  where 0 = <Result okay>.exit_code

tests/test_cli.py:164: AssertionError
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
[2018-12-07 10:31:26 INFO] Validating the experiment's syntax
[2018-12-07 10:31:26 INFO] Experiment looks valid
[2018-12-07 10:31:26 INFO] Running experiment: Check file is there
[2018-12-07 10:31:26 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-07 10:31:26 INFO] Probe: check-file-exists
[2018-12-07 10:31:26 INFO] Steady state hypothesis is met!
[2018-12-07 10:31:26 INFO] Action: remove-file
[2018-12-07 10:31:26 INFO] Steady state hypothesis: Services are all available and healthy
[2018-12-07 10:31:26 INFO] Probe: check-file-exists
[2018-12-07 10:31:26 CRITICAL] Steady state probe 'check-file-exists' is not in the given tolerance so failing this experiment
[2018-12-07 10:31:26 INFO] Let's rollback...
[2018-12-07 10:31:26 INFO] No declared rollbacks, let's move on.
[2018-12-07 10:31:26 INFO] Experiment ended with status: deviated
[2018-12-07 10:31:26 INFO] The steady-state has deviated, a weakness may have been discovered

 [...]

------------------------- generated xml file: /Users/mmi59/sky-uk/go/src/github.com/chaostoolkit/chaostoolkit/junit-test-results.xml -------------------------

---------- coverage: platform darwin, python 3.6.4-final-0 -----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
chaostoolkit/__init__.py       1      1     0%   2
chaostoolkit/__main__.py       3      3     0%   2-5
chaostoolkit/check.py         19      2    89%   37-38
chaostoolkit/cli.py          276     44    84%   74-75, 162, 202-232, 306, 386-392, 427, 438, 442-444, 452-455, 491, 502, 510
--------------------------------------------------------
TOTAL                        299     50    83%
Coverage XML written to file coverage.xml


Results (30.66s):
      22 passed
       2 failed
         - tests/test_cli.py:140 test_notify_run_failure
         - tests/test_cli.py:153 test_notify_run_failure_with_deviation

**Comment by Lawouach** [comment]
Hey @grubert65 I really need more from you at this stage if you want me to fix these because I don't own a mac and those tests don't fail on Linux nor on Travis.

**Comment by grubert65** [comment]
Ok I will investigate a bit a come with a PR

**Comment by Lawouach** [comment]
Much appreciated so that I'll release 1.0.0 afterwards (I think actually those errors are test errors more than application errors but better be sure :))

**Comment by Lawouach** [comment]
Hey @grubert65,  I was wondering if you had some feedback on this issue?
